import { DeviceRecord, DeviceStatus } from './api/devices';
import { CredentialRecord } from './api/credentials';

const addBandwidthMetrics = (devices: DeviceRecord[]): DeviceRecord[] =>
  devices.map((device) => ({
    ...device,
    interfaces: device.interfaces.map((iface, index) => {
      const capacity = iface.bandwidth_max_mbps ?? iface.max_speed ?? 1000;
      const rxCurrent = iface.rxload_current ?? iface.mbps_received ?? 0;
      const txCurrent = iface.txload_current ?? iface.mbps_sent ?? 0;
      const calculatePercent = (current: number) =>
        capacity > 0 ? Math.min(100, Math.round((current / capacity) * 100)) : 0;

      return {
        ...iface,
        bandwidth_max_mbps: capacity,
        rxload_current: rxCurrent,
        rxload_percent: iface.rxload_percent ?? calculatePercent(rxCurrent),
        txload_current: txCurrent,
        txload_percent: iface.txload_percent ?? calculatePercent(txCurrent),
        input_rate_kbps:
          iface.input_rate_kbps ??
          Math.max(0, Math.round(rxCurrent * 1000)),
        output_rate_kbps:
          iface.output_rate_kbps ??
          Math.max(0, Math.round(txCurrent * 1000)),
        mtu: iface.mtu ?? (index % 2 === 0 ? 1514 : 1500),
        crc_errors: iface.crc_errors ?? 0,
        input_errors: iface.input_errors ?? (index % 4 === 0 ? 0 : index),
        output_errors: iface.output_errors ?? (index % 3 === 0 ? 0 : index),
      };
    }),
  }));

const baseMockDevices: Array<Omit<DeviceRecord, 'status'>> = [
  {
    mac: 'a4:5e:60:1a:00:11',
    hostname: 'edge-sw1',
    primaryIp: '10.42.1.10',
    interfaces: [
      {
        interface: 'Gig0/0',
        ip_address: '10.42.1.10',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 120,
        mbps_sent: 85,
      },
      {
        interface: 'Gig0/1',
        ip_address: '10.42.1.110',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 90,
        mbps_sent: 75,
      },
      {
        interface: 'Gig0/2',
        ip_address: '10.42.1.210',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 5,
        mbps_sent: 2,
      },
      {
        interface: 'TenGig1/1',
        ip_address: 'unassigned',
        status: 'admin down',
        max_speed: 10000,
      },
    ],
    neighbors: [{ device_id: 'agg-sw1', local_interface: 'Gig0/1', port_id: 'Eth1/48' }],
    lastUpdatedAt: '2024-06-02 14:30 UTC',
    rawDate: '2024-06-02T14:30:00Z',
  },
  {
    mac: 'a4:5e:60:1a:00:12',
    hostname: 'agg-sw1',
    primaryIp: '10.42.1.11',
    interfaces: [
      {
        interface: 'Eth1/1',
        ip_address: '10.42.1.11',
        status: 'up/up',
        max_speed: 10000,
        mbps_received: 450,
        mbps_sent: 410,
      },
      {
        interface: 'Eth1/2',
        ip_address: '10.42.1.111',
        status: 'up/up',
        max_speed: 10000,
        mbps_received: 380,
        mbps_sent: 360,
      },
      {
        interface: 'Eth1/48',
        ip_address: '10.42.1.211',
        status: 'up/up',
        max_speed: 10000,
        mbps_received: 210,
        mbps_sent: 205,
      },
      {
        interface: 'Vlan10',
        ip_address: '10.10.10.2',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 55,
        mbps_sent: 40,
      },
      {
        interface: 'Vlan999',
        ip_address: 'unassigned',
        status: 'admin down',
        max_speed: 1000,
      },
    ],
    neighbors: [
      { device_id: 'edge-sw1', local_interface: 'Eth1/48', port_id: 'Gig0/1' },
      { device_id: 'core-sw2', local_interface: 'Eth1/2', port_id: 'Eth2/1' },
    ],
    lastUpdatedAt: '2024-06-02 14:20 UTC',
  },
  {
    mac: 'a4:5e:60:1a:00:13',
    hostname: 'dist-rtr1',
    primaryIp: '10.42.1.12',
    interfaces: [
      {
        interface: 'TenGig0/0/0',
        ip_address: '10.42.1.12',
        status: 'up/up',
        max_speed: 10000,
        mbps_received: 300,
        mbps_sent: 295,
      },
      {
        interface: 'TenGig0/0/1',
        ip_address: '10.42.1.112',
        status: 'up/up',
        max_speed: 10000,
        mbps_received: 250,
        mbps_sent: 240,
      },
      {
        interface: 'Gig0/0/0',
        ip_address: '10.42.2.1',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 3,
        mbps_sent: 1,
      },
      {
        interface: 'Gig0/0/1',
        ip_address: 'unassigned',
        status: 'admin down',
        max_speed: 1000,
      },
      {
        interface: 'Loopback0',
        ip_address: '172.31.0.1',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 1,
        mbps_sent: 1,
      },
    ],
    neighbors: [
      { device_id: 'agg-sw1', local_interface: 'TenGig0/0/0', port_id: 'Eth1/1' },
      { device_id: 'core-sw2', local_interface: 'TenGig0/0/1', port_id: 'Eth2/2' },
    ],
    lastUpdatedAt: '2024-06-02 14:10 UTC',
    rawDate: '2024-06-02T14:10:00Z',
  },
  {
    mac: 'a4:5e:60:1a:00:14',
    hostname: 'branch-rtr1',
    primaryIp: '10.42.1.13',
    interfaces: [
      {
        interface: 'Ether1',
        ip_address: '10.42.1.13',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 90,
        mbps_sent: 70,
      },
      {
        interface: 'Ether2',
        ip_address: '172.16.10.1',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 40,
        mbps_sent: 35,
      },
      {
        interface: 'Ether3',
        ip_address: 'unassigned',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 1,
        mbps_sent: 1,
      },
      {
        interface: 'Sfp1',
        ip_address: '10.42.1.213',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 2,
        mbps_sent: 1,
      },
    ],
    neighbors: [{ device_id: 'branch-sw2', local_interface: 'Ether1', port_id: 'Gig1/0/1' }],
    lastUpdatedAt: '2024-06-02 13:55 UTC',
  },
  {
    mac: 'a4:5e:60:1a:00:15',
    hostname: 'firewall-1',
    primaryIp: '10.42.1.14',
    interfaces: [
      {
        interface: 'Gig0/1',
        ip_address: '10.42.1.14',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 180,
        mbps_sent: 170,
      },
      {
        interface: 'Gig0/0',
        ip_address: '203.0.113.10',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 200,
        mbps_sent: 210,
      },
      {
        interface: 'Gig0/2',
        ip_address: '10.42.1.214',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 5,
        mbps_sent: 4,
      },
      {
        interface: 'Mgmt0',
        ip_address: '10.42.1.114',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 15,
        mbps_sent: 12,
      },
    ],
    neighbors: [{ device_id: 'agg-sw1', local_interface: 'Gig0/1', port_id: 'Eth1/5' }],
    lastUpdatedAt: '2024-06-02 13:40 UTC',
  },
  {
    mac: 'a4:5e:60:1a:00:16',
    hostname: 'core-sw2',
    primaryIp: '10.42.1.15',
    interfaces: [
      {
        interface: 'Mgmt0',
        ip_address: '10.42.1.15',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 60,
        mbps_sent: 55,
      },
      {
        interface: 'Eth2/1',
        ip_address: '10.42.1.115',
        status: 'up/up',
        max_speed: 10000,
        mbps_received: 500,
        mbps_sent: 480,
      },
      {
        interface: 'Eth2/2',
        ip_address: '10.42.1.215',
        status: 'down/down',
        max_speed: 10000,
        mbps_received: 5,
        mbps_sent: 4,
      },
      {
        interface: 'Vlan10',
        ip_address: '10.10.10.3',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 80,
        mbps_sent: 70,
      },
      {
        interface: 'Vlan20',
        ip_address: '10.20.20.3',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 3,
        mbps_sent: 3,
      },
    ],
    neighbors: [
      { device_id: 'agg-sw1', local_interface: 'Eth2/1', port_id: 'Eth1/2' },
      { device_id: 'dist-rtr1', local_interface: 'Eth2/2', port_id: 'TenGig0/0/1' },
      { device_id: 'dc-leaf1', local_interface: 'Vlan10' },
    ],
    lastUpdatedAt: '2024-06-02 13:25 UTC',
    rawDate: '2024-06-02T13:25:00Z',
  },
  {
    mac: 'a4:5e:60:1a:00:17',
    hostname: 'branch-sw2',
    primaryIp: '10.42.1.16',
    interfaces: [
      {
        interface: 'Gig1/0/1',
        ip_address: '10.42.1.16',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 70,
        mbps_sent: 60,
      },
      {
        interface: 'Gig1/0/2',
        ip_address: '10.42.1.116',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 65,
        mbps_sent: 58,
      },
      {
        interface: 'Gig1/0/3',
        ip_address: 'unassigned',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 2,
        mbps_sent: 1,
      },
      {
        interface: 'Gig1/0/4',
        ip_address: '10.42.1.216',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 1,
        mbps_sent: 1,
      },
    ],
    neighbors: [{ device_id: 'branch-rtr1', local_interface: 'Gig1/0/1', port_id: 'Ether1' }],
    lastUpdatedAt: '2024-06-02 13:15 UTC',
  },
  {
    mac: 'a4:5e:60:1a:00:18',
    hostname: 'dc-leaf1',
    primaryIp: '10.42.1.17',
    interfaces: [
      {
        interface: 'Eth1/1',
        ip_address: '10.42.1.17',
        status: 'up/up',
        max_speed: 10000,
        mbps_received: 520,
        mbps_sent: 500,
      },
      {
        interface: 'Eth1/2',
        ip_address: '10.42.1.117',
        status: 'up/up',
        max_speed: 10000,
        mbps_received: 480,
        mbps_sent: 460,
      },
      {
        interface: 'Eth1/3',
        ip_address: 'unassigned',
        status: 'admin down',
        max_speed: 10000,
      },
      {
        interface: 'Vlan1001',
        ip_address: '10.100.1.1',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 100,
        mbps_sent: 90,
      },
      {
        interface: 'Eth1/48',
        ip_address: '10.42.1.217',
        status: 'down/down',
        max_speed: 10000,
        mbps_received: 10,
        mbps_sent: 8,
      },
    ],
    neighbors: [
      { device_id: 'dc-leaf2', local_interface: 'Eth1/1', port_id: 'Eth1/1' },
      { device_id: 'core-sw2', local_interface: 'Eth1/2', port_id: 'Eth2/1' },
    ],
    lastUpdatedAt: '2024-06-02 13:05 UTC',
  },
  {
    mac: 'a4:5e:60:1a:00:19',
    hostname: 'dc-leaf2',
    primaryIp: '10.42.1.18',
    interfaces: [
      {
        interface: 'Eth1/1',
        ip_address: '10.42.1.18',
        status: 'up/up',
        max_speed: 10000,
        mbps_received: 510,
        mbps_sent: 490,
      },
      {
        interface: 'Eth1/2',
        ip_address: '10.42.1.118',
        status: 'up/up',
        max_speed: 10000,
        mbps_received: 470,
        mbps_sent: 450,
      },
      {
        interface: 'Eth1/3',
        ip_address: 'unassigned',
        status: 'admin down',
        max_speed: 10000,
      },
      {
        interface: 'Vlan1001',
        ip_address: '10.100.2.1',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 95,
        mbps_sent: 88,
      },
      {
        interface: 'Eth1/48',
        ip_address: '10.42.1.218',
        status: 'down/down',
        max_speed: 10000,
        mbps_received: 8,
        mbps_sent: 6,
      },
    ],
    neighbors: [
      { device_id: 'dc-leaf1', local_interface: 'Eth1/1', port_id: 'Eth1/1' },
      { device_id: 'core-sw2', local_interface: 'Eth1/2', port_id: 'Eth2/2' },
    ],
    lastUpdatedAt: '2024-06-02 12:55 UTC',
  },
  {
    mac: 'a4:5e:60:1a:00:1a',
    hostname: 'wireless-ctl1',
    primaryIp: '10.42.1.19',
    interfaces: [
      {
        interface: 'Gig0',
        ip_address: '10.42.1.19',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 140,
        mbps_sent: 130,
      },
      {
        interface: 'Gig1',
        ip_address: '10.42.1.119',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 125,
        mbps_sent: 118,
      },
      {
        interface: 'AP-Uplink1',
        ip_address: '10.42.1.219',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 5,
        mbps_sent: 4,
      },
      {
        interface: 'Mgmt1',
        ip_address: '192.168.50.5',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 30,
        mbps_sent: 25,
      },
    ],
    neighbors: [{ device_id: 'agg-sw1', local_interface: 'Gig0', port_id: 'Eth1/10' }],
    lastUpdatedAt: '2024-06-02 12:45 UTC',
  },
  {
    mac: 'a4:5e:60:1a:00:1b',
    hostname: 'voice-gw1',
    primaryIp: '10.42.1.20',
    interfaces: [
      {
        interface: 'Gi0/0/0',
        ip_address: '10.42.1.20',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 110,
        mbps_sent: 98,
      },
      {
        interface: 'Gi0/0/1',
        ip_address: '10.42.1.120',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 95,
        mbps_sent: 90,
      },
      { interface: 'FXS0/0', ip_address: 'unassigned', status: 'down/down', max_speed: 100 },
      {
        interface: 'Loopback0',
        ip_address: '172.31.255.10',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 5,
        mbps_sent: 5,
      },
    ],
    neighbors: [{ device_id: 'core-sw2', local_interface: 'Gi0/0/0', port_id: 'Eth2/3' }],
    lastUpdatedAt: '2024-06-02 12:35 UTC',
  },
  {
    mac: 'a4:5e:60:1a:00:1c',
    hostname: 'lab-sw1',
    primaryIp: '10.42.1.21',
    interfaces: [
      {
        interface: 'Gig0/0',
        ip_address: '10.42.1.21',
        status: 'up/up',
        max_speed: 1000,
        mbps_received: 60,
        mbps_sent: 55,
      },
      {
        interface: 'Gig0/1',
        ip_address: '10.42.1.121',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 2,
        mbps_sent: 1,
      },
      { interface: 'Gig0/2', ip_address: 'unassigned', status: 'admin down', max_speed: 1000 },
      {
        interface: 'Gig0/3',
        ip_address: '10.42.1.221',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 1,
        mbps_sent: 1,
      },
    ],
    neighbors: [{ device_id: 'voice-gw1', local_interface: 'Gig0/0', port_id: 'Gi0/0/1' }],
    lastUpdatedAt: '2024-06-02 12:20 UTC',
    rawDate: '2024-06-02T12:20:00Z',
  },
  {
    mac: 'a4:5e:60:1a:00:1d',
    hostname: 'old-core-sw',
    primaryIp: '10.42.1.22',
    interfaces: [
      {
        interface: 'Gi1/0',
        ip_address: '10.42.1.22',
        status: 'down/down',
        max_speed: 10000,
        mbps_received: 5,
        mbps_sent: 5,
      },
      {
        interface: 'Gi1/1',
        ip_address: '10.42.1.122',
        status: 'admin down',
        max_speed: 10000,
        mbps_received: 1,
        mbps_sent: 1,
      },
      { interface: 'Vlan1', ip_address: 'unassigned', status: 'admin down', max_speed: 1000 },
    ],
    neighbors: [],
    lastUpdatedAt: '2024-05-18 08:10 UTC',
  },
  {
    mac: 'a4:5e:60:1a:00:1e',
    hostname: 'branch-rtr2',
    primaryIp: '10.42.1.23',
    interfaces: [
      {
        interface: 'Ether1',
        ip_address: '10.42.1.23',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 3,
        mbps_sent: 2,
      },
      { interface: 'Ether2', ip_address: '172.16.20.1', status: 'admin down', max_speed: 1000 },
      {
        interface: 'Sfp1',
        ip_address: '10.42.1.223',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 1,
        mbps_sent: 1,
      },
    ],
    neighbors: [{ device_id: 'branch-sw2', local_interface: 'Sfp1', port_id: 'Gig1/0/4' }],
    lastUpdatedAt: '2024-05-18 08:00 UTC',
  },
  {
    mac: 'a4:5e:60:1a:00:1f',
    hostname: 'dmz-fw2',
    primaryIp: '10.42.1.24',
    interfaces: [
      {
        interface: 'Gig0/1',
        ip_address: '10.42.1.24',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 2,
        mbps_sent: 2,
      },
      {
        interface: 'Gig0/0',
        ip_address: '203.0.113.11',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 4,
        mbps_sent: 4,
      },
      {
        interface: 'Gig0/2',
        ip_address: '10.42.1.224',
        status: 'admin down',
        max_speed: 1000,
        mbps_received: 1,
        mbps_sent: 1,
      },
      {
        interface: 'Mgmt0',
        ip_address: '10.42.1.124',
        status: 'admin down',
        max_speed: 1000,
        mbps_received: 0.5,
        mbps_sent: 0.5,
      },
    ],
    neighbors: [],
    lastUpdatedAt: '2024-05-18 07:50 UTC',
  },
  {
    mac: 'a4:5e:60:1a:00:20',
    hostname: 'access-sw3',
    primaryIp: '10.42.1.25',
    interfaces: [
      {
        interface: 'Gig1/0/1',
        ip_address: '10.42.1.25',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 3,
        mbps_sent: 3,
      },
      { interface: 'Gig1/0/2', ip_address: '10.42.1.125', status: 'admin down', max_speed: 1000 },
      { interface: 'Gig1/0/3', ip_address: 'unassigned', status: 'admin down', max_speed: 1000 },
      {
        interface: 'TenGig1/1',
        ip_address: '10.42.1.225',
        status: 'down/down',
        max_speed: 10000,
        mbps_received: 1,
        mbps_sent: 1,
      },
    ],
    neighbors: [],
    lastUpdatedAt: '2024-05-18 07:40 UTC',
  },
  {
    mac: 'a4:5e:60:1a:00:21',
    hostname: 'remote-ap1',
    primaryIp: '10.42.1.26',
    interfaces: [
      {
        interface: 'Eth0',
        ip_address: '10.42.1.26',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 2,
        mbps_sent: 2,
      },
      {
        interface: 'Eth1',
        ip_address: '10.42.1.126',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 1,
        mbps_sent: 1,
      },
      { interface: 'Wlan0', ip_address: 'unassigned', status: 'admin down', max_speed: 300 },
    ],
    neighbors: [{ device_id: 'access-sw3', local_interface: 'Eth0', port_id: 'Gig1/0/1' }],
    lastUpdatedAt: '2024-05-18 07:30 UTC',
  },
  {
    mac: 'a4:5e:60:1a:00:22',
    hostname: 'test-sensor1',
    primaryIp: '10.42.1.27',
    interfaces: [
      {
        interface: 'Eth0',
        ip_address: '10.42.1.27',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 1,
        mbps_sent: 1,
      },
      {
        interface: 'Eth1',
        ip_address: 'unassigned',
        status: 'admin down',
        max_speed: 1000,
        mbps_received: 0.2,
        mbps_sent: 0.1,
      },
      {
        interface: 'Cellular0',
        ip_address: '10.42.1.227',
        status: 'down/down',
        max_speed: 100,
        mbps_received: 0.5,
        mbps_sent: 0.4,
      },
    ],
    neighbors: [],
    lastUpdatedAt: '2024-05-18 07:20 UTC',
  },
  {
    mac: 'b8:16:19:2c:aa:01',
    hostname: 'rogue-sw1',
    primaryIp: '10.42.1.28',
    interfaces: [
      {
        interface: 'Gi0/0',
        ip_address: '10.42.1.28',
        status: 'unauth',
        max_speed: 1000,
        mbps_received: 0.5,
        mbps_sent: 0.1,
      },
      {
        interface: 'Gi0/1',
        ip_address: '10.42.1.128',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 1,
        mbps_sent: 1,
      },
      { interface: 'Gi0/2', ip_address: 'unassigned', status: 'not authorized', max_speed: 1000 },
    ],
    neighbors: [],
    lastUpdatedAt: '2024-06-03 04:05 UTC',
    rawDate: '2024-06-03T04:05:00Z',
  },
  {
    mac: 'b8:16:19:2c:aa:02',
    hostname: 'rogue-ap1',
    primaryIp: '10.42.1.29',
    interfaces: [
      {
        interface: 'Eth0',
        ip_address: '10.42.1.29',
        status: 'unauth',
        max_speed: 1000,
        mbps_received: 0.4,
        mbps_sent: 0.3,
      },
      {
        interface: 'Wlan0',
        ip_address: 'unassigned',
        status: 'not authorized',
        max_speed: 300,
        mbps_received: 0.1,
        mbps_sent: 0.1,
      },
      {
        interface: 'Eth1',
        ip_address: '10.42.1.129',
        status: 'down/down',
        max_speed: 1000,
        mbps_received: 0.7,
        mbps_sent: 0.5,
      },
    ],
    neighbors: [],
    lastUpdatedAt: '2024-06-03 03:55 UTC',
  },
  {
    mac: 'b8:16:19:2c:aa:03',
    hostname: 'quarantined-printer',
    primaryIp: '10.42.1.30',
    interfaces: [
      {
        interface: 'Eth0',
        ip_address: '10.42.1.30',
        status: 'unauth',
        max_speed: 100,
        mbps_received: 0.2,
        mbps_sent: 0.1,
      },
      {
        interface: 'Eth1',
        ip_address: '10.42.1.130',
        status: 'down/down',
        max_speed: 100,
        mbps_received: 0.3,
        mbps_sent: 0.2,
      },
      { interface: 'Eth2', ip_address: 'unassigned', status: 'admin down', max_speed: 100 },
    ],
    neighbors: [],
    lastUpdatedAt: '2024-06-03 03:45 UTC',
  },
];

const mockStatuses: Record<string, DeviceStatus> = {
  'edge-sw1': 'active',
  'agg-sw1': 'active',
  'dist-rtr1': 'active',
  'branch-rtr1': 'active',
  'firewall-1': 'active',
  'core-sw2': 'active',
  'branch-sw2': 'active',
  'dc-leaf1': 'active',
  'dc-leaf2': 'active',
  'wireless-ctl1': 'active',
  'voice-gw1': 'active',
  'lab-sw1': 'active',
  'old-core-sw': 'inactive',
  'branch-rtr2': 'inactive',
  'dmz-fw2': 'inactive',
  'access-sw3': 'inactive',
  'remote-ap1': 'inactive',
  'test-sensor1': 'inactive',
  'rogue-sw1': 'unauthorized',
  'rogue-ap1': 'unauthorized',
  'quarantined-printer': 'unauthorized',
};

export const mockDevices: DeviceRecord[] = addBandwidthMetrics(
  baseMockDevices.map((device) => ({
    ...device,
    status: mockStatuses[device.hostname] ?? 'inactive',
  }))
);

export const mockCredentials: CredentialRecord[] = [
  { device_type: 'cisco_ios', username: 'netops', password: 'Net0ps!', secret: 'C1sco!23', ip: '10.42.1.10' },
  { device_type: 'cisco_nxos', username: 'admin', password: 'Nexus#9000', secret: 'NxEnable', ip: '10.42.1.11' },
  {
    device_type: 'cisco_iosxe',
    username: 'automation',
    password: 'Aut0mation!',
    secret: 'C1sc0Enable',
    ip: '10.42.1.12',
  },
  { device_type: 'mikrotik', username: 'mtadmin', password: 'm1kroT1k!', ip: '10.42.1.13', snmp_password: 'mtSnmp$' },
  { device_type: 'cisco_asa', username: 'asaops', password: 'As@Strong!', secret: 'FWsecret!', ip: '10.42.1.14' },
  { device_type: 'cisco_nxos', username: 'core', password: 'C0reSwitch!', ip: '10.42.1.15', snmp_password: 'SnmpC0re' },
  { device_type: 'cisco_ios', username: 'field', password: 'Fi3ld!', secret: 'Access!', ip: '10.42.1.16' },
  { device_type: 'cisco_nxos', username: 'leaf', password: 'LeafPass!1', ip: '10.42.1.17', snmp_password: 'SnmpLeaf1' },
  { device_type: 'cisco_nxos', username: 'leaf2', password: 'LeafPass!2', ip: '10.42.1.18', snmp_password: 'SnmpLeaf2' },
  { device_type: 'cisco_iosxe', username: 'wlcadmin', password: 'Wlc#2024', secret: 'WlcSecret', ip: '10.42.1.19' },
  { device_type: 'cisco_ios', username: 'voiceops', password: 'V01ce!', secret: 'GwSecret', ip: '10.42.1.20' },
  { device_type: 'cisco_ios', username: 'lab', password: 'LabPass!1', secret: 'LabEnable', ip: '10.42.1.21' },
  { device_type: 'juniper_junos', username: 'jadmin', password: 'Jun0s!', ip: '10.42.1.22', snmp_password: 'Jun1perSNMP' },
  { device_type: 'mikrotik', username: 'field2', password: 'M1kro!', ip: '10.42.1.23', snmp_password: 'FieldSnmp' },
  { device_type: 'cisco_asa', username: 'dmzops', password: 'Dmz!1234', secret: 'DmzSecret', ip: '10.42.1.24' },
  { device_type: 'cisco_ios', username: 'access', password: 'Acc3ss!', secret: 'AccSecret', ip: '10.42.1.25' },
  { device_type: 'juniper_junos', username: 'apadmin', password: 'ApAdm1n!', ip: '10.42.1.26', snmp_password: 'ApSnmp' },
  { device_type: 'mikrotik', username: 'sensor', password: 'Sens0r!', ip: '10.42.1.27', snmp_password: 'SensorSNMP' },
];
